parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            adha8y38hafhpaufyjadhsf89pGIUGIUG

    easybacklog_api.api_key:          xsxsxsxsxsx
    easybacklog_api.url:              https://easybacklog.com
    easybacklog_api.userid:           xsxsxsxsxssx

    teams:
        teama:
            name:   Team A
            backlog:  32573
        teamb:
            name:   Team B
            backlog:  23574
        teamc:
            name:   Team C
            backlog:  23566

    memcached.servers:
      - { host: 127.0.0.1, port: 11211 }
    #  - { host: 192.168.0.101, port: 11211 }  